import { QueryInterface } from "sequelize";

export default {
    up: async (queryInterface: QueryInterface) => {
        await queryInterface.bulkInsert('medicines', [
            {
                name: 'novalgina',
                active_principle: 'dipirona monoidratada',
                composition: 'Cada mL contém 50 mg de dipirona monoidratada./nExcipientes: sacarose líquida, formaldeído bissulfito de sódio, sorbato de potássio, benzoato de sódio, ácido cítrico anidro, corante eritrosina, essência de framboesa, água purific',
                presentation: 'solução oral (infantil) 50 mg/ml: frascos com 100 ml + seringa dosadora',
                use: 'administre o conteúdo da seringa diretamente na boca do paciente',                 
                drug_interactions: 'Indução farmacocinética de enzimas metabolizadoras:/n A dipirona pode induzir enzimas metabolizadoras, incluindo CYP2B6 e CYP3A4.A co-administração de dipirona com substratos do CYP2B6 e/ou CYP3A4, como bupropiona, efavirenz, metadona, ciclosporina, tacrolimus ou sertralina, pode causar uma redução nas concentrações plasmáticas destes medicamentos. Portanto, recomenda-se cautela quando dipirona e substrato de CYP2B6 e/ou CYP3A4 são administrados concomitantemente; a resposta clínica e/ou os níveis do medicamento devem ser seguidos de monitoramento terapêutico do medicamento. /n valproato: A dipirona pode diminuir os níveis séricos de valproato quando coadministrado, o que pode resultar em eficácia potencialmente diminuída do valproato. Os prescritores devem monitorar a resposta clínica (controle das convulsões ou controle do humor) e considerar o monitoramento dos níveis séricos de valproato, conforme apropriado. Adicionar dipirona ao metotrexato pode aumentar a hematotoxicidade do metotrexato, particularmente em pacientes idosos. Portanto, esta combinação deve ser evitada. A dipirona pode reduzir o efeito do ácido acetilsalicílico na agregação plaquetária, quando tomado concomitantemente. Portanto, esta combinação deve ser usada com cautela em pacientes que tomam ácido acetil salicílico em baixas doses para proteção cardiovascular. /n Medicamento-alimentos: não há dados disponíveis até o momento sobre a interação entre alimentos e dipirona. /n Medicamento-exames laboratoriais: foram reportadas interferências em testes laboratoriais que utilizam reações de Trinder (por exemplo: testes para medir níveis séricos de creatinina, triglicérides, colesterol HDL e ácido úrico) em pacientes utilizando dipirona.'
            }, 
            {
                name: 'novalgina', 
                active_principle: 'dipirona monoidratada',
                composition: 'NOVALGINA 500 mg: Cada comprimido contém 500 mg de dipirona monoidratada./n Excipientes: estearato de magnésio, macrogol 4000. NOVALGINA 1 g: Cada comprimido contém 1000 mg de dipirona monoidratada. Excipientes: estearato de magnésio, macrogol 4000.',
                presentation: 'Comprimidos 500 mg: embalagem com 30, 100 ou 240. /n Comprimidos 1 g: embalagem com 10 ou 100.', 
                use: 'Tomar o comprimido com líquido (aproximadamente ½ a 1 copo), por via oral./n Este medicamento não deve ser mastigado.',
                drug_interactions: 'Indução farmacocinética de enzimas metabolizadoras:/n A dipirona pode induzir enzimas metabolizadoras, incluindo CYP2B6 e CYP3A4.A co-administração de dipirona com substratos do CYP2B6 e/ou CYP3A4, como bupropiona, efavirenz, metadona, ciclosporina, tacrolimus ou sertralina, pode causar uma redução nas concentrações plasmáticas destes medicamentos. Portanto, recomenda-se cautela quando dipirona e substrato de CYP2B6 e/ou CYP3A4 são administrados concomitantemente; a resposta clínica e/ou os níveis do medicamento devem ser seguidos de monitoramento terapêutico do medicamento. /n valproato: A dipirona pode diminuir os níveis séricos de valproato quando coadministrado, o que pode resultar em eficácia potencialmente diminuída do valproato. Os prescritores devem monitorar a resposta clínica (controle das convulsões ou controle do humor) e considerar o monitoramento dos níveis séricos de valproato, conforme apropriado. Adicionar dipirona ao metotrexato pode aumentar a hematotoxicidade do metotrexato, particularmente em pacientes idosos. Portanto, esta combinação deve ser evitada. A dipirona pode reduzir o efeito do ácido acetilsalicílico na agregação plaquetária, quando tomado concomitantemente. Portanto, esta combinação deve ser usada com cautela em pacientes que tomam ácido acetil salicílico em baixas doses para proteção cardiovascular. /n Medicamento-alimentos: não há dados disponíveis até o momento sobre a interação entre alimentos e dipirona. /n Medicamento-exames laboratoriais: foram reportadas interferências em testes laboratoriais que utilizam reações de Trinder (por exemplo: testes para medir níveis séricos de creatinina, triglicérides, colesterol HDL e ácido úrico) em pacientes utilizando dipirona.'
            }, 
            {
                name: 'omeprazol',
                active_principle: 'omeprazol',
                composition: 'Cada cápsula de Gastrium 40 mg contém: omeprazol 40 mg Excipientes: sacarose, manitol, carbonato de cálcio, fosfato de sódio dibásico, laurilsulfato de sódio, metilparabeno sódico, propilparabeno, povidona, hipromelose, polimetacrilicocopoliacrilato de etila, dietilftalato, dióxido de titânio, talco, polissorbato 80 e hidróxido de sódio. ',
                presentation: 'Cápsula dura de liberação retardada 20mg',
                use: 'Você deve tomar as cápsulas com líquido, por via oral imediatamente antes das refeições, preferencialmente pela manhã. Para pacientes que tiverem dificuldade em engolir, as cápsulas podem ser abertas e os microgrânulos intactos misturados com pequena quantidade de suco de frutas ou água fria e tomadas imediatamente. Os microgrânulos não devem ser mastigados e nem misturados com leite antes da administração. Pode demorar vários dias até que ocorra alívio das dores estomacais. Para ajudar no alívio dessas dores, podem ser usados antiácidos junto com omeprazol, salvo orientação contrária do seu médico. Utilize este medicamento durante o tratamento estabelecido pelo seu médico e mesmo que você já esteja se sentindo bem, só interrompa o tratamento quando seu médico assim determinar. /n -Adultos Úlceras duodenais: 20mg uma vez ao dia, antes do café da manhã, durante duas a quatro semanas. /n Úlceras gástricas e esofagite de refluxo: 20mg uma vez ao dia, antes do café da manhã, durante quatro a oito semanas. /n Profilaxia de úlceras duodenais e esofagite de refluxo: 10mg ou 20mg antes do café da manhã. /n Síndrome de Zollinger-Ellison: a dosagem deve ser individualizada de maneira a se administrar a menor dose capaz de reduzir a secreção gástrica adequadamente. A posologia inicial é normalmente de 60mg em dose única; posologias superiores a 80mg ao dia ser administradas em duas vezes. /n -Esofagite de refluxo em crianças Crianças com mais de 1 ano de idade: 10mg em dose única administrada pela manhã com o auxílio de líquido (água ou suco de frutas; mas não leite). /n Crianças acima de 20kg: 20mg. Caso a criança tenha dificuldade para engolir, as cápsulas podem ser abertas e o seu conteúdo pode ser misturado com líquido (água ou suco de frutas;mas não em leite) e ingerido imediatamente. Se necessária, a dose poderá ser aumentada, a critério médico, até, no máximo, 40mg ao dia. /n Siga a orientação de seu médico, respeitando sempre os horários, as doses e a duração do tratamento. Não interrompa o tratamento sem o conhecimento do seu médico. ',
                drug_interactions: 'O uso de omeprazol com alguns tipos de medicamentos não é recomendado, mas poderá ser necessário. Nesses casos, seu médico poderá alterar a dose e a frequência dos medicamentos, como por exemplo: atazanavir, clorazepato, delavirdine, metotrexato. '
            },
            {
                name: 'dorflex',
                active_principle: 'citrato de orfenadrina/ dipirona sódica/ cafeína anidra',
                composition: 'Cada comprimido contém: citrato de orfenadrina 35 mg, dipirona sódica monoidratada 300 mg, cafeína anidra 50 mg, excipientes q.s.p 1 comprimido, (amido de milho, amidoglicolato de sódio, talco e estearato de magnésio). ',
                presentation: 'COMPRIMIDOS: Caixas com 8, 24, 30, 144, 192, 220, 240, 288 ou 480 comprimidos. SOLUÇÃO ORAL(GOTAS): Frascos com 20 ml',
                use: 'Comprimidos: Recomenda-se que os comprimidos sejam deglutidos sem mastigar e com líquido suficiente (aproximadamente ½ a 1 copo). ',
                drug_interactions: 'Confusão, ansiedade e tremores foram relatados em alguns pacientes que receberam orfenadrina concomitantemente com propoxifeno. Os fenotiazínicos, como a clorpromazina, podem interferir no controle da termorregulação corporal, causando tanto hipotermia como hipertermia. A dipirona sódica pode potencializar eventual hipotermia causada por fenotiazínicos. Agentes anticolinérgicos, como a orfenadrina, não controlam a discinesia tardia associada ao use prolongado de antipsicóticos. Seu uso pode mesmo exacerbar os sintomas de liberação extrapiramidal associados a estas drogas. A dipirona sódica pode causar redução dos níveis plasmáticos de ciclosporina. Deve-se, portanto, realizar monitorização das concentrações de ciclosporina quando da administração concomitante de dipirona sódica./n Alimentos : Não há dados disponíveis até o momento sobre a administração concomitante de alimentos e DORFLEX®. /n Exames de laboratório Não há dados disponíveis até o momento sobre a interferência de DORFLEX® em exames de laboratório. '
            },
            {
                name: 'neosoro',
                active_principle: 'cloridrato de nafazolina', 
                composition: 'Cada mL (30 gotas)* da solução gotas contém: cloridrato de nafazolina  0,5mg, veículo q.s.p 1mL, (cloreto de benzalcônio, cloreto de sódio e água). *Cada gota contém 0,017mg de cloridrato de nafazolina. ',
                presentation: 'solução gotas. Embalagem contendo 1 frasco com 30ml',
                use: 'Gotejar 2 a 4 gotas em cada narina, 4 a 6 vezes ao dia. A dose máxima diária não deverá ultrapassar 48 gotas. O intervalo de tempo entre as administrações não deve ser menor do que 3 horas. ',
                drug_interactions: 'Recomenda-se precaução no e do produto nos pacientes em tratamento com inibidores da monoaminoxidase. O uso concomitante de NEOSORO com antidepressivos tricíclicos pode levar a uma potencialização dos efeitos pressóricos da nafazolina. O uso concomitante com levalbuterol pode potencializar os efeitos cardiovasculares da nafazolina Observação: Embora estas reações não sejam específicas da nafazolina, a possibilidade de interação medicamentosa deve ser considerada. '
            }, {
                name: 'neosaldina',
                active_principle: 'dipirona monoidratada/ mucato de isometepteno/ cafeina',
                composition: 'Cada drágea contém 300 mg de dipirona, 30 mg de mucato de isometepteno e 30 mg de cafeína anidra. Excipientes: amido, carbonato de cálcio, carmelose sódica, celulose microcristalina, cera branca de abelha, cera de carnaúba, dióxido de silício, estearato de magnésio, goma arábica, lactose, metilparabeno, povidona, propilparabeno, sacarose, talco, dióxido de titânio, laca vermelha e pigmento marrom.',
                presentation: 'Drágea de 300 mg (dipirona) + 30 mg (mucato de isometepteno) + 30 mg (cafeína). Embalagens com 20, 30, 100, 200 e 240 unidades.',
                use: 'NEOSALDINA® é de uso exclusivo pela via oral (por boca). Posologia: 1 a 2 drágeas (em dose única) a cada 6 horas ou 4 vezes ao dia. Não tome mais de 8 drágeas ao dia (4 x 2 drágeas). Este medicamento não deve ser partido, aberto ou mastigado. Siga corretamente o modo de usar. Em caso de dúvidas sobre este medicamento, procure orientação do farmacêutico.',
                drug_interactions: 'NEOSALDINA® junto com bebidas alcoólicas, nem com medicamentos que contenham clorpromazina (usada no tratamento de doenças psiquiátricas) ou ciclosporina (usada em pacientes transplantados) A cafeína pode reduzir a ação sedativa dos ansiolíticos/benzodiazepínicos (medicamentos usados para dormir ou tratar ansiedade). Podem ocorrer reações hipertensivas (aumento da pressão arterial) com o uso juntamente com antidepressivos inibidores da monoaminoxidase (IMAOs) (Alguns remédios usados para tratar depressão).'
            }, 
            {
                name: 'losartana potássica',
                active_principle: 'losartana potássica',
                composition: 'Cada comprimido revestido de losartana potássica contém: losartana potássica 50,00 mg, Excipientes: lactose monoidratada, amido, dióxido de silício, estearato de magnésio, celulose microcristalina, hipromelose, macrogol e dióxido de titânio.',
                presentation: 'Comprimidos revestidos de 50 mg: embalagem com 30 comprimidos revestidos.',
                use: 'Losartana potássica pode ser tomada com ou sem alimentos. Para maior comodidade e para se lembrar com mais facilidade, tente tomar este medicamento no mesmo horário todos os dias. Tome losartana potássica diariamente, exatamente conforme a orientação de seu médico. Seu médico irá decidir a dose adequada de losartana potássica dependendo do seu estado de saúde e dos outros medicamentos que você estiver tomando. É importante que continue tomando losartana potássica pelo tempo que o médico lhe receitar, para manter a pressão arterial controlada.',
                drug_interactions: 'em geral, losartana potássica não interage com alimentos ou outros medicamentos que você possa estar tomando. Entretanto, seu médico deve ser informado sobre todos os medicamentos que você toma, tomou recentemente ou pretende tomar, incluindo os que são vendidos sem receita. É importante informar ao seu médico se estiver tomando: - Outros medicamentos que diminuem a pressão sanguínea, pois eles podem reduzi-la ainda mais. A pressão sanguínea pode ser reduzida por um destes medicamentos ou uma destas classes de medicamentos: antidepressivos tricíclicos, antipsicóticos, baclofeno e amifostina; - Medicamentos que retêm potássio ou podem aumentar seus níveis (por exemplo, suplementos de potássio, substitutos do sal da dieta que contêm potássio ou medicamentos poupadores de potássio como alguns diuréticos (amilorida, triantereno e espironolactona), heparina ou produtos que contenham trimetoprima); - Anti-inflamatórios não esteroidais tais como indometacina, incluindo inibidores da COX-2 (medicamentos que reduzem a inflamação e podem ser utilizados no auxílio do alívio da dor), porque podem reduzir o efeito da losartana potássica na diminuição da pressão sanguínea. Seu médico pode ter que mudar a dose que você está utilizando e/ou tomar outras precauções se você estiver tomando um inibidor de ECA ou alisquireno (veja os itens “3. Quando não devo usar este medicamento?” e “4. O que devo saber antes de usar este medicamento?”). Se o funcionamento de seus rins estiver prejudicado, o uso destes medicamentos juntamente com losartana potássica poderá levar a uma piora no funcionamento deles. Medicamentos que contêm lítio (um medicamento usado para o tratamento de certos tipos de depressão) não devem ser utilizados juntamente com a losartana sem a supervisão cuidadosa do seu médico. Precauções especiais (como exames de sangue) podem ser indicadas.'
            }
        ], {});
    },
    down: async (queryInterface: QueryInterface) => {
        await queryInterface.bulkDelete('medicines', {});
    },
};